<script type="text/javascript">
<!--

document.write( '<!doctype html>\n' );
document.write( '\n' );
document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '  <meta charset=\"utf-8\">\n' );
document.write( '  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n' );
document.write( '\n' );
document.write( '  <title>CSCI441 Group 2 Gifting Site</title>\n' );
document.write( '  <meta name=\"description\" content=\"CSCI441 Group 2 Final Project\">\n' );
document.write( '  <meta name=\"author\" content=\"CSCI441 Group 2\">\n' );
document.write( '\n' );
document.write( '  <meta property=\"og:title\" content=\"CSCI441 Group 2 Final Project\">\n' );
document.write( '  <meta property=\"og:type\" content=\"website\">\n' );
document.write( '  <meta property=\"og:description\" content=\"A site for helping pick out gifts for your friends.\">\n' );
document.write( '\n' );
document.write( '  <link rel=\"icon\" href=\"images/favicon.ico\">\n' );
document.write( '  <link rel=\"icon\" href=\"images/favicon.svg\" type=\"image/svg+xml\">\n' );
document.write( '  <link rel=\"account icon\" href=\"images/acct.png\">\n' );
document.write( '\n' );
document.write( '  <link href=\"public/css/bootstrap.min.css\" rel=\"stylesheet\">\n' );
document.write( '  <link rel=\"stylesheet\" href=\"public/css/styles.css\">\n' );
document.write( '</head>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<body>\n' );
document.write( '\n' );
document.write( ' \n' );
document.write( '\n' );
document.write( '  <!-- Nav menu here-->\n' );
document.write( '<div class=\"container-fluid navbar\" height=\"80px\">\n' );
document.write( '<a href=\"index.php\" class=\"logo\"><img src=\"images/logo.png\" height=\"80px\" width=\"324px\"></a>\n' );
document.write( '\n' );
document.write( '<nav id=\"mainnav\">\n' );
document.write( '\n' );
document.write( '  <a href=\"html/browse.html\">Browse For Items</a>\n' );
document.write( '  <a href=\"html/friendLists.html\">Manage Friend List</a>\n' );
document.write( '  <a href=\"html/contactUs.html\">Contact Us</a>\n' );
document.write( '  <a href=\"html/about.html\">About</a>\n' );
document.write( '  <a href=\"html/howToUse.html\">How to Use This Site</a>\n' );
document.write( '  <a href=\"html/logIn.html\" id=\"login\">Log In</a>\n' );
document.write( '  \n' );
document.write( '  </nav>\n' );
document.write( '\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '<div class=\"container-fluid\" max-height=\"100%\">\n' );
document.write( '\n' );
document.write( '  <h1>testing</h1>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<div class=\".container\"></div>\n' );
document.write( '  <!--\n' );
document.write( '  \n' );
document.write( '  image of happy couple here\n' );
document.write( '\n' );
document.write( 'rotating images of items -  size dependent on window size-->\n' );
document.write( '\n' );
document.write( '<!--\n' );
document.write( '\n' );
document.write( 'We do we want and what do we know\n' );
document.write( '\n' );
document.write( '4 items, will be an array, with buttons under them for adding to the list.\n' );
document.write( '\n' );
document.write( 'The array will be objects, probably some kind of JSON object, from amazon, with data\n' );
document.write( '\n' );
document.write( 'Inside each column will be the data, with a button below it that will open either a modal or a popover to add to a list.\n' );
document.write( '\n' );
document.write( 'The lists will be stored in the database, per user...somehow.\n' );
document.write( '\n' );
document.write( 'Probably by storing the account ID in the session state, and then querying the database based on that?\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '-->\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<div class=\"container-sm text-center\">\n' );
document.write( '\n' );
document.write( '  <div class=\"row\">\n' );
document.write( '\n' );
document.write( '    <div class=\"col\" id=\"item1\">\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <div class=\"col\" id=\"item2\">\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <div class=\"col\" id=\"item3\">\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <div class=\"col\" id=\"item4\">\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '  <!--footer here-->\n' );
document.write( '  <div class=\"container-fluid footer\">\n' );
document.write( '\n' );
document.write( '    \n' );
document.write( '    <p>All rights reserved. Copyright 2023</p>  \n' );
document.write( '      <p>This site is for demonstration purposes only.</p>\n' );
document.write( '      \n' );
document.write( '      <span class=\"botnav\">\n' );
document.write( '      <a href=\"html/privacyPolicy.html\">Privacy Policy</a> |\n' );
document.write( '      <a href=\"html/termsOfUse.html\">Terms of Use</a> |\n' );
document.write( '      <a href=\"html/careers.html\">Careers</a>\n' );
document.write( '      <span>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '  <script>\n' );
document.write( '\n' );
document.write( '  sessionStorage.setItem(\"boo\", \"true\");\n' );
document.write( '\n' );
document.write( '  </script>\n' );
document.write( '</body>\n' );
document.write( '</html>' );

//-->
</script>
